import React, { useState, useEffect } from 'react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { db } from '../services/mockData';
import { formatCurrency } from '../constants';
import { Unit, Property, RoomStatus, Resident } from '../types';
import { Home, Users, CreditCard, Info, ChevronRight, MapPin, Download } from 'lucide-react';

// Status computation logic for table display
interface RoomsProps {
  ownerId: string;
  initialPropertyId: string | null;
  onUpgrade: () => void;
  assignedPropertyIds?: string[];
  onViewResident?: (residentId: string) => void;
}

const Rooms: React.FC<RoomsProps> = ({ 
  ownerId, 
  initialPropertyId, 
  onUpgrade, 
  assignedPropertyIds,
  onViewResident 
}) => {
  const [properties, setProperties] = useState<Property[]>([]);
  const [selectedPropId, setSelectedPropId] = useState<string>(initialPropertyId || 'all');
  const [units, setUnits] = useState<Unit[]>([]);
  const [residents, setResidents] = useState<Resident[]>([]);
  const [loading, setLoading] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);
  
  // Modal States
  const [showAddModal, setShowAddModal] = useState(false);
  const [showViewModal, setShowViewModal] = useState(false);
  const [editingUnitId, setEditingUnitId] = useState<string | null>(null);
  const [viewingUnit, setViewingUnit] = useState<Unit | null>(null);

  const fetchData = async () => {
    setLoading(true);
    try {
      const [propsData, unitsData, residentsData] = await Promise.all([
        db.getProperties(ownerId),
        db.getUnits(ownerId),
        db.getResidents(ownerId)
      ]);
      setProperties(propsData);
      setUnits(unitsData);
      setResidents(residentsData);
    } catch (error) {
      console.error("Error fetching rooms data:", error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, [ownerId]);

  const getUnitStatus = (u: Unit) => {
    if (u.status === RoomStatus.MAINTENANCE) return RoomStatus.MAINTENANCE;
    if (u.currentOccupants === 0) return RoomStatus.VACANT;
    if (u.currentOccupants < u.capacity) return RoomStatus.PARTIAL;
    return RoomStatus.FULL;
  };

  const filteredUnits = selectedPropId === 'all' 
    ? units 
    : units.filter(u => u.propertyId === selectedPropId);

  const handleDownloadPDF = () => {
    const doc = new jsPDF('l', 'pt', 'a4');
    const propertyName = selectedPropId === 'all' ? 'All Properties' : (properties.find(p => p.id === selectedPropId)?.name || 'Property');
    
    // Add Header
    doc.setFontSize(20);
    doc.setTextColor(15, 23, 42); // slate-900
    doc.text('Room Inventory Detail Report', 40, 50);
    
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text(`Property: ${propertyName}`, 40, 70);
    doc.text(`Date: ${new Date().toLocaleDateString('en-IN')}`, 40, 85);
    doc.text(`Generated by: Hostel Management Pro`, 40, 100);

    // Stats Section
    doc.setDrawColor(241, 245, 249); // slate-100
    doc.setFillColor(248, 250, 252); // slate-50
    doc.roundedRect(40, 115, 760, 40, 10, 10, 'FD');
    
    doc.setFontSize(9);
    doc.setTextColor(71, 85, 105); // slate-600
    doc.text(`Total Rooms: ${stats.total}`, 60, 140);
    doc.text(`Available: ${stats.vacant}`, 200, 140);
    doc.text(`Partial: ${stats.partial}`, 340, 140);
    doc.text(`Full: ${stats.full}`, 480, 140);

    // Table Data
    const tableData = filteredUnits.map(u => {
      const status = getUnitStatus(u);
      return [
        u.roomNumber,
        u.propertyName,
        u.type,
        `${u.currentOccupants} / ${u.capacity}`,
        formatCurrency(u.price),
        status,
        u.tenantName || '-'
      ];
    });

    autoTable(doc, {
      startY: 170,
      head: [['Room', 'Property', 'Type', 'Occupancy', 'Rent/Bed', 'Status', 'Current Tenant']],
      body: tableData,
      theme: 'grid',
      headStyles: { 
        fillColor: [15, 23, 42], 
        textColor: 255, 
        fontSize: 9, 
        fontStyle: 'bold',
        halign: 'center'
      },
      columnStyles: {
        0: { halign: 'left', fontStyle: 'bold' },
        1: { halign: 'left' },
        2: { halign: 'center' },
        3: { halign: 'center' },
        4: { halign: 'right' },
        5: { halign: 'center' },
        6: { halign: 'left' }
      },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      styles: { fontSize: 8, cellPadding: 8, overflow: 'linebreak' },
      didDrawCell: (data: any) => {
        if (data.column.index === 5 && data.section === 'body') {
          const status = data.cell.raw;
          if (status === RoomStatus.VACANT) doc.setTextColor(16, 185, 129); // emerald-500
          else if (status === RoomStatus.PARTIAL) doc.setTextColor(59, 130, 246); // blue-500
          else if (status === RoomStatus.FULL) doc.setTextColor(15, 15, 15); // black
          else if (status === RoomStatus.MAINTENANCE) doc.setTextColor(245, 158, 11); // orange-500
        }
      }
    });

    doc.save(`Room_Inventory_${propertyName.replace(/\s+/g, '_')}_${new Date().toLocaleDateString('en-IN')}.pdf`);
  };

  const stats = {
    total: filteredUnits.length,
    vacant: filteredUnits.filter(u => getUnitStatus(u) === RoomStatus.VACANT).length,
    partial: filteredUnits.filter(u => getUnitStatus(u) === RoomStatus.PARTIAL).length,
    full: filteredUnits.filter(u => getUnitStatus(u) === RoomStatus.FULL).length,
  };

  // Add/Edit Room Form State
  const [formPropId, setFormPropId] = useState(initialPropertyId || '');
  const [roomNumber, setRoomNumber] = useState('');
  const [roomType, setRoomType] = useState('1'); // '1', '2', '3', '4', '5', 'custom'
  const [customShare, setCustomShare] = useState('');
  const [rent, setRent] = useState('');
  const [floor, setFloor] = useState('');
  const [isMaintenance, setIsMaintenance] = useState(false);
  const [amenities, setAmenities] = useState<Record<string, boolean>>({
    AC: false, WiFi: false, 'Attached Bath': false, Balcony: false, TV: false, Fridge: false
  });
  const [notes, setNotes] = useState('');

  const resetForm = () => {
    setFormPropId(initialPropertyId || '');
    setRoomNumber('');
    setRoomType('1');
    setCustomShare('');
    setRent('');
    setFloor('');
    setNotes('');
    setIsMaintenance(false);
    setAmenities({
      AC: false, WiFi: false, 'Attached Bath': false, Balcony: false, TV: false, Fridge: false
    });
    setEditingUnitId(null);
  };

  const handleEditClick = (u: Unit) => {
    setEditingUnitId(u.id);
    setFormPropId(u.propertyId);
    setRoomNumber(u.roomNumber);
    setFloor(u.floorNumber);
    setRent(u.price.toString());
    setNotes(u.notes || '');
    setIsMaintenance(u.status === RoomStatus.MAINTENANCE);
    
    const capacityVal = u.capacity.toString();
    if (['1', '2', '3', '4', '5'].includes(capacityVal)) {
      setRoomType(capacityVal);
    } else {
      setRoomType('custom');
      setCustomShare(capacityVal);
    }

    const newAmenities = { ...amenities };
    Object.keys(newAmenities).forEach(key => {
      newAmenities[key] = u.amenities.includes(key);
    });
    setAmenities(newAmenities);
    
    setShowAddModal(true);
  };

  const handleViewClick = (u: Unit) => {
    setViewingUnit(u);
    setShowViewModal(true);
  };

  const handleSubmitRoom = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    setFormError(null);

    const prop = properties.find(p => p.id === formPropId);
    const capacity = roomType === 'custom' ? parseInt(customShare) : parseInt(roomType);
    const currentOccupants = editingUnitId ? (units.find(u => u.id === editingUnitId)?.currentOccupants || 0) : 0;
    
    // Recalculate status based on new capacity and existing occupancy
    let calculatedStatus: RoomStatus = RoomStatus.VACANT;
    if (isMaintenance) {
      calculatedStatus = RoomStatus.MAINTENANCE;
    } else if (currentOccupants === 0) {
      calculatedStatus = RoomStatus.VACANT;
    } else if (currentOccupants < capacity) {
      calculatedStatus = RoomStatus.PARTIAL;
    } else {
      calculatedStatus = RoomStatus.FULL;
    }

    const unitData: Unit = {
      id: editingUnitId || `UNIT-${Date.now()}`,
      ownerId,
      propertyId: formPropId,
      propertyName: prop?.name || 'Unknown',
      roomNumber,
      type: `${capacity}-share`,
      capacity: capacity || 1,
      currentOccupants,
      price: parseInt(rent) || 0,
      status: calculatedStatus,
      floorNumber: floor,
      amenities: Object.keys(amenities).filter(k => amenities[k]),
      tenantName: editingUnitId ? (units.find(u => u.id === editingUnitId)?.tenantName || '-') : '-',
      notes
    };

    try {
      if (editingUnitId) {
        await db.updateUnit(unitData);
      } else {
        await db.saveUnit(unitData);
      }

      await fetchData();
      setShowAddModal(false);
      resetForm();
    } catch (error) {
      console.error("Error saving room:", error);
      setFormError(error instanceof Error ? error.message : "Failed to save room. Please try again.");
    } finally {
      setIsSubmitting(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
      </div>
    );
  }

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      {/* Header & Filter */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
        <div>
          <h1 className="text-3xl font-black text-slate-900 tracking-tight uppercase">Room Management</h1>
          <p className="text-slate-500 font-medium">Configure and monitor individual living units.</p>
        </div>
        <div className="flex items-center gap-4 w-full md:w-auto">
          <div className="relative flex-1 md:flex-none">
            <select 
              value={selectedPropId} 
              onChange={(e) => setSelectedPropId(e.target.value)}
              className="w-full md:w-56 px-4 py-3 bg-white border border-slate-200 rounded-xl text-xs font-black uppercase tracking-widest appearance-none pr-10 outline-none focus:ring-4 focus:ring-blue-500/5 focus:border-blue-500 transition-all shadow-sm"
            >
              <option value="all">All Properties</option>
              {properties.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}
            </select>
            <svg className="w-4 h-4 absolute right-3.5 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" /></svg>
          </div>
          <button 
            onClick={() => { resetForm(); setShowAddModal(true); }}
            className="bg-blue-600 text-white px-6 py-3 rounded-xl font-black uppercase tracking-widest text-xs hover:bg-blue-700 transition-all flex items-center gap-3 shadow-xl shadow-blue-100 hover:-translate-y-0.5"
          >
            <span className="text-xl leading-none">+</span> Add Room
          </button>
        </div>
      </div>

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 md:gap-6">
        <div className="bg-white p-3 md:p-8 rounded-xl md:rounded-[2rem] border border-slate-100 shadow-sm text-center group hover:border-blue-100 transition-all">
          <p className="text-xl md:text-5xl font-black text-slate-900 mb-1 group-hover:scale-105 transition-transform">{stats.total}</p>
          <p className="text-[7px] md:text-[10px] font-black text-slate-400 uppercase tracking-widest leading-none">Total Rooms</p>
        </div>
        <div className="bg-emerald-50/50 p-3 md:p-8 rounded-xl md:rounded-[2rem] border border-emerald-100 shadow-sm text-center">
          <p className="text-xl md:text-5xl font-black text-emerald-600 mb-1">{stats.vacant}</p>
          <p className="text-[7px] md:text-[10px] font-black text-emerald-400 uppercase tracking-widest leading-none">Available Now</p>
        </div>
        <div className="bg-blue-50/50 p-3 md:p-8 rounded-xl md:rounded-[2rem] border border-blue-100 shadow-sm text-center">
          <p className="text-xl md:text-5xl font-black text-blue-600 mb-1">{stats.partial}</p>
          <p className="text-[7px] md:text-[10px] font-black text-blue-400 uppercase tracking-widest leading-none">Partially Occupied</p>
        </div>
        <div className="bg-slate-900 p-3 md:p-8 rounded-xl md:rounded-[2rem] border border-slate-800 shadow-sm text-center">
          <p className="text-xl md:text-5xl font-black text-white mb-1">{stats.full}</p>
          <p className="text-[7px] md:text-[10px] font-black text-slate-400 uppercase tracking-widest leading-none">Full Rooms</p>
        </div>
      </div>

      {/* Table Section */}
      <div className="bg-white rounded-[1.5rem] md:rounded-[2.5rem] border border-slate-100 shadow-sm overflow-hidden">
        <div className="p-6 md:p-10 border-b border-slate-50 bg-slate-50/30 flex items-center justify-between">
          <div>
            <h3 className="font-black text-slate-900 uppercase tracking-widest text-sm mb-1">Room Inventory Details</h3>
            <p className="text-slate-400 text-[10px] md:text-xs font-medium">Real-time status tracking for all units across {properties.length} properties</p>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={handleDownloadPDF}
              className="flex items-center gap-2 px-4 py-2 bg-slate-900 text-white rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-slate-800 transition-all shadow-lg shadow-slate-100"
            >
              <Download className="w-3 h-3" />
              Download Inventory PDF
            </button>
          </div>
        </div>
        <div className="overflow-hidden">
          {/* Desktop Table View */}
          <div className="hidden md:block overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                  <tr className="bg-slate-50/80 text-[10px] font-black text-slate-400 uppercase tracking-widest border-b border-slate-100">
                    <th className="px-10 py-6">Room</th>
                    <th className="px-10 py-6">Property</th>
                    <th className="px-10 py-6">Type</th>
                    <th className="px-10 py-6">Beds (Occ/Total)</th>
                    <th className="px-10 py-6">Rent / Bed</th>
                    <th className="px-10 py-6">Status</th>
                    <th className="px-10 py-6">Current Tenant</th>
                    <th className="px-10 py-6 text-right">Options</th>
                  </tr>
              </thead>
              <tbody className="divide-y divide-slate-50">
                {filteredUnits.length === 0 ? (
                  <tr>
                    <td colSpan={8} className="px-10 py-32 text-center">
                       <div className="max-w-xs mx-auto text-slate-300">
                          <svg className="w-12 h-12 mx-auto mb-4 opacity-50" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" /></svg>
                          <p className="font-bold italic">No room configurations found in this property group.</p>
                       </div>
                    </td>
                  </tr>
                ) : (
                  filteredUnits.map((u) => {
                    const status = getUnitStatus(u);
                    return (
                      <tr 
                        key={u.id} 
                        onClick={() => handleViewClick(u)}
                        className="hover:bg-slate-50/50 transition-all group cursor-pointer"
                      >
                        <td className="px-10 py-8 group/room">
                           <p className="font-black text-slate-900 text-base leading-tight mb-1 group-hover:text-blue-600 transition-colors truncate">{u.roomNumber}</p>
                           <p className="text-[10px] text-slate-400 font-bold uppercase tracking-tight">FL {u.floorNumber || '0'}</p>
                        </td>
                        <td className="px-10 py-8 text-sm font-bold text-slate-600 leading-snug max-w-[150px] truncate">{u.propertyName}</td>
                        <td className="px-10 py-8 text-[10px] font-black uppercase text-slate-400 tracking-widest">{u.type}</td>
                        <td className="px-10 py-8">
                           <span className="px-2 py-1 bg-slate-100 rounded-lg text-[10px] font-black text-slate-600 whitespace-nowrap">{u.currentOccupants} / {u.capacity} BEDS</span>
                        </td>
                        <td className="px-10 py-8 font-black text-slate-900 text-base">{formatCurrency(u.price)}</td>
                        <td className="px-10 py-8 min-w-[140px]">
                          <span className={`inline-block px-3 py-2 rounded-xl text-[9px] font-black uppercase tracking-tight shadow-sm border leading-tight ${
                            status === RoomStatus.VACANT ? 'bg-emerald-50 text-emerald-600 border-emerald-100' :
                            status === RoomStatus.PARTIAL ? 'bg-blue-50 text-blue-600 border-blue-100' :
                            status === RoomStatus.FULL ? 'bg-slate-900 text-white border-slate-900' :
                            'bg-orange-50 text-orange-600 border-orange-100'
                          }`}>
                            {status}
                          </span>
                        </td>
                        <td className="px-10 py-8 text-sm font-bold text-slate-500">{u.tenantName || '-'}</td>
                        <td className="px-10 py-8 text-right">
                          <div className="flex justify-end gap-4 text-[10px] font-black uppercase tracking-widest text-slate-300">
                            <button 
                              onClick={(e) => { e.stopPropagation(); handleViewClick(u); }} 
                              className="hover:text-blue-600 transition-colors"
                            >
                              View
                            </button>
                            <button 
                              onClick={(e) => { e.stopPropagation(); handleEditClick(u); }} 
                              className="hover:text-slate-900 transition-colors"
                            >
                              Edit
                            </button>
                          </div>
                        </td>
                      </tr>
                    );
                  })
                )}
              </tbody>
            </table>
          </div>

          {/* Mobile List View */}
          <div className="md:hidden divide-y divide-slate-100">
            {filteredUnits.length === 0 ? (
              <div className="px-6 py-20 text-center">
                <p className="text-slate-400 font-bold italic text-sm">No rooms found.</p>
              </div>
            ) : (
              filteredUnits.map((u) => {
                const status = getUnitStatus(u);
                const occupancyPercent = (u.currentOccupants / u.capacity) * 100;
                
                return (
                  <div 
                    key={u.id} 
                    onClick={() => handleViewClick(u)}
                    className="p-6 active:bg-slate-50 transition-colors relative group"
                  >
                    <div className="flex justify-between items-start mb-4">
                      <div className="flex gap-3">
                        <div className="w-12 h-12 bg-slate-50 rounded-2xl flex items-center justify-center text-slate-400 group-active:text-blue-600 transition-colors border border-slate-100">
                          <Home className="w-6 h-6" />
                        </div>
                        <div>
                          <div className="flex items-center gap-2 mb-1">
                            <h4 className="text-xl font-black text-slate-900">{u.roomNumber}</h4>
                            <span className="px-1.5 py-0.5 bg-blue-50 text-blue-600 rounded text-[9px] font-black uppercase tracking-tight border border-blue-100">FL {u.floorNumber || '0'}</span>
                          </div>
                          <div className="flex items-center gap-1 text-slate-400">
                            <MapPin className="w-3 h-3" />
                            <p className="text-[10px] font-bold uppercase tracking-widest truncate max-w-[120px]">{u.propertyName}</p>
                          </div>
                        </div>
                      </div>
                      <div className="text-right">
                        <p className="text-lg font-black text-slate-900">{formatCurrency(u.price)}</p>
                        <p className="text-[9px] font-bold text-slate-400 uppercase tracking-tight">per bed</p>
                      </div>
                    </div>

                    <div className="flex items-center justify-between gap-4">
                      <div className="flex-1">
                        <div className="flex justify-between items-center mb-1.5">
                          <div className="flex items-center gap-1 text-slate-400">
                            <Users className="w-3 h-3" />
                            <span className="text-[9px] font-black uppercase tracking-widest">Occupancy</span>
                          </div>
                          <span className="text-[9px] font-black text-slate-900 uppercase tracking-tight">{u.currentOccupants}/{u.capacity} Beds</span>
                        </div>
                        <div className="h-1.5 w-full bg-slate-100 rounded-full overflow-hidden">
                          <div 
                            className={`h-full rounded-full transition-all duration-500 ${
                              status === RoomStatus.FULL ? 'bg-slate-900' : 
                              status === RoomStatus.PARTIAL ? 'bg-blue-500' : 
                              'bg-emerald-500'
                            }`}
                            style={{ width: `${occupancyPercent}%` }}
                          ></div>
                        </div>
                      </div>
                      <div className="shrink-0 flex items-center gap-2">
                        <span className={`inline-block px-2.5 py-1.5 rounded-lg text-[8px] font-black uppercase tracking-widest border leading-none ${
                          status === RoomStatus.VACANT ? 'bg-emerald-50 text-emerald-600 border-emerald-100' :
                          status === RoomStatus.PARTIAL ? 'bg-blue-50 text-blue-600 border-blue-100' :
                          status === RoomStatus.FULL ? 'bg-slate-900 text-white border-slate-900' :
                          'bg-orange-50 text-orange-600 border-orange-100'
                        }`}>
                          {status}
                        </span>
                        <ChevronRight className="w-4 h-4 text-slate-300" />
                      </div>
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </div>
      </div>

      {/* View Room Modal */}
      {showViewModal && viewingUnit && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-slate-900/40 " onClick={() => setShowViewModal(false)}></div>
          <div className="relative bg-white w-full max-w-lg rounded-[2rem] md:rounded-[2.5rem] shadow-2xl animate-in zoom-in duration-300 flex flex-col max-h-[90vh] border border-slate-100">
            <div className="p-6 md:p-10 pb-0 relative shrink-0">
              <button onClick={() => setShowViewModal(false)} className="absolute top-6 md:top-10 right-6 md:right-10 text-slate-400 hover:text-slate-600 transition">
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" /></svg>
              </button>
              <h2 className="text-2xl md:text-3xl font-black text-slate-900 uppercase tracking-tight">Room Details</h2>
              <p className="text-slate-500 text-[10px] md:text-sm mt-1 font-medium italic">Unit Information for Room {viewingUnit.roomNumber}</p>
            </div>
            
            <div className="p-6 md:p-10 space-y-6 md:space-y-8 overflow-y-auto scrollbar-hide">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 md:gap-8">
                <div>
                   <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Property Name</p>
                   <p className="font-bold text-slate-900 leading-snug text-sm md:text-base">{viewingUnit.propertyName}</p>
                </div>
                <div>
                   <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Room / Floor</p>
                   <p className="font-bold text-slate-900 leading-snug text-sm md:text-base">{viewingUnit.roomNumber} (Floor {viewingUnit.floorNumber})</p>
                </div>
                <div>
                   <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Unit Type</p>
                   <p className="font-bold text-slate-900 uppercase text-sm md:text-base">{viewingUnit.type}</p>
                </div>
                <div>
                   <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Beds</p>
                   <p className="font-bold text-slate-900 text-sm md:text-base">{viewingUnit.currentOccupants} Occupied / {viewingUnit.capacity} Total</p>
                </div>
                <div>
                   <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Rent per Bed</p>
                   <p className="font-bold text-slate-900 text-lg md:text-xl leading-none mt-1">{formatCurrency(viewingUnit.price)}</p>
                </div>
                <div>
                   <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Status</p>
                   <span className={`inline-block px-3 py-2 rounded-lg text-[9px] font-black uppercase tracking-tight mt-1 border leading-tight ${
                      getUnitStatus(viewingUnit) === RoomStatus.VACANT ? 'bg-emerald-50 text-emerald-600 border-emerald-100' :
                      getUnitStatus(viewingUnit) === RoomStatus.PARTIAL ? 'bg-blue-50 text-blue-600 border-blue-100' :
                      getUnitStatus(viewingUnit) === RoomStatus.FULL ? 'bg-slate-900 text-white border-slate-900' :
                      'bg-orange-50 text-orange-600 border-orange-100'
                    }`}>
                      {getUnitStatus(viewingUnit)}
                    </span>
                </div>
              </div>

              <div>
                <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-3">Amenities</p>
                <div className="flex flex-wrap gap-2">
                  {viewingUnit.amenities.length > 0 ? viewingUnit.amenities.map(a => (
                    <span key={a} className="px-3 py-1.5 bg-slate-50 border border-slate-100 rounded-xl text-[10px] font-black text-slate-600 uppercase whitespace-nowrap">{a}</span>
                  )) : <p className="text-xs text-slate-400 italic">No amenities listed.</p>}
                </div>
              </div>

              {viewingUnit.notes && (
                <div>
                   <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Management Notes</p>
                   <p className="text-sm text-slate-600 leading-relaxed font-medium">{viewingUnit.notes}</p>
                </div>
              )}

              <div className="pt-6 border-t border-slate-100">
                <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-4 flex items-center gap-2">
                  <svg className="w-4 h-4 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" /></svg>
                  Current Occupants ({viewingUnit.currentOccupants})
                </p>
                <div className="space-y-3">
                  {residents.filter(r => r.unitId === viewingUnit.id && r.status === 'active').length > 0 ? (
                    residents.filter(r => r.unitId === viewingUnit.id && r.status === 'active').map(r => (
                      <div 
                        key={r.id} 
                        onClick={() => onViewResident && onViewResident(r.id)}
                        className="flex items-center justify-between p-4 bg-slate-50 rounded-2xl border border-slate-100 group hover:border-blue-200 transition-all cursor-pointer"
                      >
                        <div className="flex items-center gap-3">
                          <div className="w-10 h-10 rounded-xl bg-blue-600 text-white flex items-center justify-center font-black text-xs shadow-lg shadow-blue-100">
                            {r.name[0]}
                          </div>
                          <div>
                            <p className="text-sm font-black text-slate-900">{r.name}</p>
                            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-tight">Joined {new Date(r.moveInDate).toLocaleDateString('en-IN', { dateStyle: 'medium' })}</p>
                          </div>
                        </div>
                        <div className="text-right">
                          <p className="text-[10px] font-black text-blue-600 uppercase tracking-widest">Active</p>
                          <p className="text-[9px] font-bold text-slate-400 mt-0.5">{r.phone}</p>
                        </div>
                      </div>
                    ))
                  ) : (
                    <div className="p-6 text-center bg-slate-50 rounded-2xl border border-dashed border-slate-200">
                      <p className="text-xs font-bold text-slate-400 italic">No active residents in this room.</p>
                    </div>
                  )}
                </div>
              </div>

              <div className="pt-4 sticky bottom-0 bg-white pb-2">
                <button 
                  onClick={() => { setShowViewModal(false); handleEditClick(viewingUnit); }}
                  className="w-full py-4 bg-slate-900 text-white font-black uppercase tracking-widest text-xs rounded-2xl shadow-xl shadow-slate-200 hover:-translate-y-0.5 transition"
                >
                  Edit Unit Configuration
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Add / Edit Room Modal */}
      {showAddModal && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-slate-900/40 " onClick={() => { setShowAddModal(false); resetForm(); }}></div>
          <div className="relative bg-white w-full max-w-xl rounded-[2rem] shadow-2xl animate-in zoom-in duration-300 flex flex-col max-h-[90vh] border border-slate-100">
            <div className="p-6 md:p-10 pb-4 relative shrink-0">
              <button onClick={() => { setShowAddModal(false); resetForm(); }} className="absolute top-6 md:top-10 right-6 md:right-10 text-slate-400 hover:text-slate-600 transition">
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" /></svg>
              </button>
              <h2 className="text-xl md:text-3xl font-black text-slate-900 uppercase tracking-tight">{editingUnitId ? 'Edit Room' : 'Add New Room'}</h2>
              <p className="text-slate-500 text-[10px] md:text-sm mt-1 font-medium italic">{editingUnitId ? 'Modify existing configuration' : 'Configure unit capacity, amenities and pricing'}</p>
            </div>

            {formError && (
              <div className="mx-6 md:mx-10 mb-4 p-4 bg-rose-50 border border-rose-100 rounded-2xl text-rose-600 text-xs font-bold">
                {formError}
              </div>
            )}

            <form onSubmit={handleSubmitRoom} className="p-6 md:p-10 pt-4 space-y-6 overflow-y-auto scrollbar-hide flex-1">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                <div className="space-y-2">
                  <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">Assigned Property</label>
                  <div className="relative">
                    <select 
                      required 
                      value={formPropId} 
                      onChange={(e) => setFormPropId(e.target.value)}
                      className="w-full px-4 py-3 bg-slate-50 border border-slate-100 rounded-xl outline-none focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 transition-all text-sm font-bold appearance-none pr-10"
                    >
                      <option value="">Select property</option>
                      {properties.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}
                    </select>
                    <svg className="w-4 h-4 absolute right-3.5 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" /></svg>
                  </div>
                </div>
                <div className="space-y-2">
                  <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">Room Label/Number</label>
                  <input required value={roomNumber} onChange={(e) => setRoomNumber(e.target.value)} type="text" placeholder="e.g., 101A" className="w-full px-4 py-3 bg-slate-50 border border-slate-100 rounded-xl outline-none focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 transition-all text-sm font-bold" />
                </div>
              </div>

              <div className="space-y-2">
                <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">Unit Type (Sharing)</label>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
                   {['1', '2', '3', '4', '5'].map(val => (
                     <button
                       key={val}
                       type="button"
                       onClick={() => setRoomType(val)}
                       className={`py-3 rounded-xl text-[10px] md:text-xs font-black uppercase border transition-all ${
                         roomType === val 
                         ? 'bg-blue-600 text-white border-blue-600 shadow-lg shadow-blue-100' 
                         : 'bg-white text-slate-400 border-slate-200 hover:border-blue-300'
                       }`}
                     >
                       {val}-Share
                     </button>
                   ))}
                   <button
                     type="button"
                     onClick={() => setRoomType('custom')}
                     className={`py-3 rounded-xl text-[10px] md:text-xs font-black uppercase border transition-all ${
                       roomType === 'custom' 
                       ? 'bg-blue-600 text-white border-blue-600 shadow-lg shadow-blue-100' 
                       : 'bg-white text-slate-400 border-slate-200 hover:border-blue-300'
                     }`}
                   >
                     + Custom
                   </button>
                </div>
              </div>

              {roomType === 'custom' && (
                <div className="space-y-2 animate-in slide-in-from-top-2 duration-300">
                  <label className="text-[10px] font-black text-blue-600 uppercase tracking-widest ml-1">Enter Custom Share Number</label>
                  <input 
                    required 
                    value={customShare} 
                    onChange={(e) => setCustomShare(e.target.value)} 
                    type="number" 
                    placeholder="e.g., 6" 
                    className="w-full px-4 py-3 bg-blue-50/50 border border-blue-100 rounded-xl outline-none focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 transition-all text-sm font-bold" 
                  />
                </div>
              )}

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                <div className="space-y-2">
                  <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">Rent / Bed</label>
                  <div className="relative">
                    <span className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 font-bold">₹</span>
                    <input 
                      required 
                      value={rent} 
                      onChange={(e) => setRent(e.target.value)} 
                      type="number" 
                      placeholder="Rent amount" 
                      className="w-full pl-8 pr-4 py-3 bg-slate-50 border border-slate-100 rounded-xl outline-none focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 transition-all text-sm font-bold" 
                    />
                  </div>
                </div>
                <div className="space-y-2">
                  <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">Floor</label>
                  <input required value={floor} onChange={(e) => setFloor(e.target.value)} type="text" placeholder="e.g. 2nd" className="w-full px-4 py-3 bg-slate-50 border border-slate-100 rounded-xl outline-none focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 transition-all text-sm font-bold" />
                </div>
              </div>

              <div className="flex items-center gap-3 bg-slate-50 p-4 rounded-2xl border border-slate-100">
                <input 
                  type="checkbox" 
                  id="maintenance-mode"
                  checked={isMaintenance}
                  onChange={(e) => setIsMaintenance(e.target.checked)}
                  className="w-5 h-5 rounded border-slate-300 text-blue-600 focus:ring-blue-500"
                />
                <label htmlFor="maintenance-mode" className="text-[10px] md:text-xs font-bold text-slate-600 uppercase tracking-tight cursor-pointer">Set room under maintenance</label>
              </div>

              <div className="space-y-4">
                <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">Amenities</label>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-y-4">
                  {Object.keys(amenities).map(amenity => (
                    <label key={amenity} className="flex items-center gap-3 cursor-pointer group">
                      <div className="relative inline-flex items-center">
                        <input 
                          type="checkbox" 
                          checked={amenities[amenity]} 
                          onChange={(e) => setAmenities({...amenities, [amenity]: e.target.checked})} 
                          className="sr-only peer" 
                        />
                        <div className="w-10 h-6 bg-slate-200 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600 shadow-sm border border-slate-100"></div>
                      </div>
                      <span className="text-[9px] md:text-[10px] font-black text-slate-500 group-hover:text-slate-900 transition-colors uppercase tracking-tight">{amenity}</span>
                    </label>
                  ))}
                </div>
              </div>

              <div className="space-y-2">
                <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">Notes / Description</label>
                <textarea 
                  value={notes} 
                  onChange={(e) => setNotes(e.target.value)} 
                  rows={2} 
                  placeholder="Additional details about room location or specific features" 
                  className="w-full px-4 py-3 bg-slate-50 border border-slate-100 rounded-xl outline-none focus:ring-4 focus:ring-blue-500/10 focus:border-blue-500 transition-all text-sm font-bold resize-none" 
                />
              </div>

              <div className="flex gap-4 pt-4 sticky bottom-0 bg-white pb-2">
                <button 
                  type="button" 
                  disabled={isSubmitting}
                  onClick={() => { setShowAddModal(false); resetForm(); }} 
                  className="flex-1 py-4 border border-slate-100 text-slate-400 font-black uppercase tracking-widest text-xs rounded-xl hover:bg-slate-50 transition-all disabled:opacity-50"
                >
                  Cancel
                </button>
                <button 
                  type="submit" 
                  disabled={isSubmitting}
                  className="flex-1 py-4 bg-blue-600 text-white font-black uppercase tracking-widest text-xs rounded-xl hover:bg-blue-700 transition-all shadow-xl shadow-blue-100 disabled:opacity-50 flex items-center justify-center gap-2"
                >
                  {isSubmitting ? (
                    <>
                      <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                      Saving...
                    </>
                  ) : (
                    editingUnitId ? 'Update Room' : 'Add Room'
                  )}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default Rooms;